spring:
  application:
    name: Ziniumanas
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/newsman_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  thymeleaf:
    cache: false
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
model:
  save:
    path: models/bert_classifier
  epochs: 5
  learning:
    rate: 0.0001
logging:
  level:
    lt.ziniumanas: DEBUG
    ai.djl: INFO