spring:
  application:
    name: Ziniumanas
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/newsman_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  thymeleaf:
    cache: false # Išjungia Thymeleaf talpyklą vystymo metu
server:
  port: 8081
  error:
    whitelabel:
      enabled: false
model:
  save:
    path: "data/ArticleCategorizationAImodel.zip"
paragraph:
  vectors:
    save:
      path: "data/paragraph_vectors.zip"
    epochs: 1
    min:
      word:
        frequency: 0
    layer:
      size: 100
    learning:
      rate: 0.025
    window:
      size: 5
logging:
  level:
    lt.ziniumanas: DEBUG # Detalesnis logavimas jūsų paketams
    org.deeplearning4j: INFO
    org.nd4j: INFO