spring:
  application:
    name: Ziniumanas
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/newsman_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  thymeleaf:
    cache: false
  web:
    resources:
      add-mappings: false
  mvc:
    dispatch-options-request: true
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active:
      dev
server:
  port: 8080
  error:
    whitelabel:
      enabled: false

logging:
  level:
    org.springframework: DEBUG
    lt.ziniumanas: DEBUG

classification:
  api:
    url: http://localhost:5000/predict