spring:
  application:
    name: Ziniumanas
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/newsman_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false
  thymeleaf:
    cache: false
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
model:
  save:
    path: C:/Users/Admin/IdeaProjects/Ziniumanas/models/custom-distilbert
  epochs: 5
  learning:
      rate: 0.0001
logging:
  level:
    org.springframework: DEBUG
    lt.ziniumanas: DEBUG
    ai.djl: DEBUG
ai:
  djl:
    default_engine: PyTorch
nlp:
  model:
    path: C:/Users/Admin/IdeaProjects/Ziniumanas/models/custom-distilbert
    file: custom-bert.pt
    name: distilbert-base-multilingual-cased
    maxlength: 256
    epochs: 5
    learning-rate: 0.0001